databases:
  - name: sanctuary-db
    plan: free
    databaseName: sanctuary
    user: sanctuary

services:
  - type: web
    name: sanctuary
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python -m gunicorn wellbeing_project.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sanctuary-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DEMO_PASSWORD
        sync: false
      - key: DEMO_USERNAME
        value: Demo
      - key: DEMO_EMAIL
        value: demo@example.com
      - key: DEMO_DAYS
        value: "90"
