module.exports = {
    content: [
        "./tracker/templates/**/*.html",
        "./tracker/static/js/**/*.js",
    ],
    theme: {
        extend: {
            colors: {
                "surface-dim": "#dbdad5",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#1b1c19",
                "error-container": "#ffdad6",
                "on-tertiary-fixed-variant": "#4f4537",
                "on-secondary-container": "#48697a",
                "secondary": "#426374",
                "secondary-container": "#c5e7fc",
                "on-secondary-fixed": "#001e2b",
                "tertiary-container": "#807463",
                "primary-fixed": "#caebd0",
                "secondary-fixed-dim": "#aacbdf",
                "surface-tint": "#486550",
                "tertiary": "#665c4c",
                "on-primary": "#ffffff",
                "primary": "#47644f",
                "background": "#fbf9f4",
                "on-background": "#1b1c19",
                "on-primary-fixed": "#042110",
                "primary-container": "#5f7d67",
                "tertiary-fixed-dim": "#d3c4b1",
                "on-primary-fixed-variant": "#304d3a",
                "inverse-primary": "#aeceb5",
                "on-tertiary": "#ffffff",
                "surface-container": "#f0eee9",
                "surface-container-high": "#eae8e3",
                "on-tertiary-fixed": "#221a0e",
                "surface-container-low": "#f5f3ee",
                "outline": "#727972",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#c5e7fc",
                "on-tertiary-container": "#fffeff",
                "on-error-container": "#93000a",
                "on-primary-container": "#ffffff",
                "primary-fixed-dim": "#aeceb5",
                "on-secondary-fixed-variant": "#2a4b5b",
                "on-error": "#ffffff",
                "outline-variant": "#c2c8c1",
                "surface-bright": "#fbf9f4",
                "on-surface-variant": "#424843",
                "inverse-on-surface": "#f2f1ec",
                "error": "#ba1a1a",
                "surface-container-highest": "#e4e2dd",
                "tertiary-fixed": "#f0e0cc",
                "surface": "#fbf9f4",
                "surface-variant": "#e4e2dd",
                "inverse-surface": "#30312e",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                unit: "8px",
                "margin-mobile": "16px",
                "margin-desktop": "24px",
                gutter: "24px",
            },
            fontFamily: {
                "headline-md": ["Manrope", "sans-serif"],
                "headline-lg": ["Manrope", "sans-serif"],
                "display-lg": ["Manrope", "sans-serif"],
                "body-lg": ["Manrope", "sans-serif"],
                "body-md": ["Manrope", "sans-serif"],
                "label-md": ["Manrope", "sans-serif"],
                "label-sm": ["Manrope", "sans-serif"],
                "headline-sm": ["Manrope", "sans-serif"],
            },
            fontSize: {
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
                "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
            },
        },
    },
};
