# Generated by Django 5.2.13 on 2026-05-04 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_bedtime", models.TimeField()),
                ("target_wake_time", models.TimeField()),
                ("caffeine_cutoff", models.TimeField()),
                (
                    "weekly_exercise_goal",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "wellbeing_focus",
                    models.CharField(
                        choices=[
                            ("sleep", "Better Sleep"),
                            ("energy", "More Energy"),
                            ("routine", "Better Routine"),
                            ("mood", "Better Mood"),
                        ],
                        default="sleep",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField()),
                ("bedtime", models.TimeField()),
                ("wake_time", models.TimeField()),
                (
                    "sleep_quality",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "evening_screen_time",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("under_30", "Under 30 minutes"),
                            ("30_60", "30–60 minutes"),
                            ("1_2", "1–2 hours"),
                            ("2_plus", "2+ hours"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caffeine_consumed", models.BooleanField(default=False)),
                ("latest_caffeine_time", models.TimeField(blank=True, null=True)),
                ("exercise_completed", models.BooleanField(default=False)),
                (
                    "energy_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "mood_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "entry_date"),
                        name="unique_daily_entry_per_user",
                    )
                ],
            },
        ),
    ]
